Add action buttons
zetkin/app.zetkin.org pull request #1103
Opened 2023-03-18 00:49 UTC by niklasva82

## Description
This PR adds an action button menu to create surveys, tasks, and call assignments.

## Screenshots
[Screencast from 2023-03-18 01-43-59.webm](https://user-images.githubusercontent.com/14962107/226074153-37663666-cc4b-4393-ad6e-e9ccc366c4b1.webm)

## Changes
* Adds new ZUIButtonMenu component
* Adds elements to that ButtonMenu to create surveys, call assignments and tasks
* Adds model, repo and store for campaign and uses it to create surveys and call assignments.
* Uses the old modal from the ZUISpeedDial to create tasks.
* Removes ZUISpeedDial from all single campaign view and campaigns calendar view which was missed before.

## Notes to reviewer

## Related issues
Resolves #1018

2023-03-18 02:23 UTC, niklasva82 commented
I noticed there was an issue with the menu being open after clicking, so I modified the ZUIButtonMenu to override the onClick prop of its children and close the menu before running the child's onClick. This works fine, but I have not been able to get Typescript to agree, I have no idea why it's complaining, but after trying a bunch of solutions, I ended up adding a //@ts-ignore

2023-03-18 11:04 UTC, richardolsson requested changes
I'm sorry to hear you struggled with typescript. Please reach out when you have problems like that. We really don't want to disable typescript anywhere, unless it's extremely special cases, and I don't think this is a valid such case.

I committed a change to that part of the code, which uses the same pattern as the similar `ZUIEllipsisMenu` component, in using a strongly typed `items` property instead of the vaguely typed children, to define the contents of the menu.

I also found something to be unexpected in your PR, which is that you've created a new store slice. Can you explain?

2023-03-18 11:04 UTC, richardolsson commented on src/features/campaigns/store.ts
> +});
What's the purpose of this? There is already a store slice for call assignments, and another one for surveys. I see no need for having a store slice called `campaign` where the same data is stored.

2023-03-19 10:35 UTC, richardolsson approved these changes
I've changed the things I did not like, so IMO it's ready for merging!

2023-03-19 10:35 UTC, merged