Check if tag is in list before concat
zetkin/app.zetkin.org pull request #1124
Opened 2023-03-21 22:30 UTC by theo8theo8

## Description
This PR fixes the bug where a disabled tag could be added over and over.

## Changes
* Before concatenating the added tag to the list, checks that it is not already in it.

## Related issues
Closes #922

2023-03-23 13:58 UTC, richardolsson requested changes
Awesome! Thank you so much for contributing. I'm very impressed by how you were able to navigate the codebase and find a solution to this.

Unless I'm mistaken, this bug is actually in the `TagManager` (or `TagSelectList`) and not just in this particular use case. I'm able to reproduce it (with a slight variation) in other places, e.g. here where clicking a tag that has already been selected makes a request to reassign it.

http://app.dev.zetkin.org/organize/1/journeys/1/6

It looks to me like `TagSelectList` handles clicks on tag chips without checking `disabled`.

https://github.com/zetkin/app.zetkin.org/blob/b46110d8297bd2ef337e7f0302aa9f27e517fb00/src/features/tags/components/TagManager/components/TagSelect/TagSelectList.tsx#L50-L56

Would you be willing to take a look at fixing this "at the source" @theo8theo8?

2023-03-23 16:24 UTC, theo8theo8 commented
> 

Thanks, looking forward to helping out with the project.
Oh, that seems very reasonable, will take a look at it in the next few days!

2023-03-25 18:41 UTC, theo8theo8 commented
I believe this should be fixed now, please let me know if I misunderstood where the problem was.

2023-03-25 19:18 UTC, richardolsson commented
> @richardolsson I believe this should be fixed now, please let me know if I misunderstood where the problem was.

Nice work! You didn't misunderstand me, but I now think that my suggestion was not the best one. What you've done now is basically what I was imagining, but as I was reviewing your code I realized that maybe it's better if `TagChip` internally checks its `disabled` property before calling its `onClick()`.

What do you think @theo8theo8?

2023-03-25 20:13 UTC, theo8theo8 commented
> > @richardolsson I believe this should be fixed now, please let me know if I misunderstood where the problem was.
> 
> Nice work! You didn't misunderstand me, but I now think that my suggestion was not the best one. What you've done now is basically what I was imagining, but as I was reviewing your code I realized that maybe it's better if `TagChip` internally checks its `disabled` property before calling its `onClick()`.
> 
> What do you think @theo8theo8?

I agree with you. Probably better to do it as internally as possible. I was looking at that before, but it took a bit of time to understand the propagations of the onclicks.

2023-03-26 20:42 UTC, theo8theo8 commented
Not sure if you saw it @richardolsson, no stress, but my last commit fixed your concerns.

2023-03-27 03:56 UTC, richardolsson approved these changes
Very minimalistic and clean! Nice work 🙌

2023-03-27 04:07 UTC, merged

2023-03-27 04:08 UTC, richardolsson commented
I squashed the PR into a single commit and merged it, since in the end it only made a small change (but a big improvement!). Great work! May we mention you in our release notes @theo8theo8? 😊

2023-03-27 06:19 UTC, theo8theo8 commented
> I squashed the PR into a single commit and merged it, since in the end it only made a small change (but a big improvement!). Great work! May we mention you in our release notes @theo8theo8? 😊

Thanks, seems very reasonable. Of course :)