Organizer action view
zetkin/app.zetkin.org pull request #1187
Opened 2023-04-03 03:39 UTC by niklasva82

## Description
This PR…

## Screenshots
[Add screenshots here]

## Changes
[Add a list of features added/changed, bugs fixed etc]

* Adds…
* Changes…

## Notes to reviewer
[Add instructions for testing]

## Related issues
Resolves #[id]

2023-04-03 03:41 UTC, niklasva82 commented
Not sure what to do about this.
![bild](https://user-images.githubusercontent.com/14962107/229406193-62ad04d3-fc83-4106-9570-c272c9b55547.png)

I'm just doing the same thing as createNew/server.ts in order to get messages server-side in the getOrganizerAction rpc.

2023-04-04 15:06 UTC, richardolsson commented
@niklasva82 The problem you had when trying to internationalize your RPC is that the same RPC module imported both server-side and client-side code, and was used in the browser (which is throwing an error because the module is trying to import server-only code, `fs`).

This is solved by separating the client-side code from the server-side code in the RPC as I've done here.

2023-04-05 14:05 UTC, richardolsson requested changes
I have now looked through all the code more thoroughly (after just getting it to work when I first took over the PR).

The comments below are the things I found that I will be changing. I'm just leaving them as comments to share the feedback.

2023-04-05 14:05 UTC, richardolsson commented on src/features/callAssignments/models/CallAssignmentModel.ts
> +  }
These aren't used anywhere, the ones in `CallModel` are.

2023-04-06 04:52 UTC, richardolsson approved these changes
I've fixed all the issues I found in my previous review so I'm going to go ahead and merge this now. 😊

2023-04-06 04:52 UTC, merged