Implement post event participant attendance
zetkin/app.zetkin.org pull request #1320
Opened 2023-05-08 23:42 UTC by niklasva82

## Description
This PR adds the ability to set wether participants attended after the event.

## Screenshots
![bild](https://user-images.githubusercontent.com/14962107/236959613-5cbbe9f4-61dd-4021-9ae1-3c7dc8f3bbc0.png)

## Changes
* Adds buttons for attended and noshow
* Refactor the way buttons and dropdowns were rendered into separate components, it was getting a bit too messy.

## Related issues
Resolves #1220

2023-05-09 06:02 UTC, richardolsson requested changes
I think the solution looks great in general, but it's missing a couple of features.

* The "book" button under signups as been lost. I'm not sure what would be the best solution here, whether there should be attendance buttons in the signups list after the event or not, but at the very least we still need the book button, especially before an event takes place.
* The requirements concerning the summary at the top of the page are not met. Please have a look at the requirements list and design mockups in the issue #1220 for details.

2023-05-09 23:01 UTC, niklasva82 commented on src/features/events/components/ParticipantListSection.tsx
> +              options={[
It seems I forgot about the book button when reimplementing. This has been fixed.

The options are different before and after for the booked list, but not the others.

2023-05-09 23:01 UTC, niklasva82 commented
[Screencast from 2023-05-10 00-56-09.webm](https://github.com/zetkin/app.zetkin.org/assets/14962107/89b6d6de-c824-447c-849a-4cd1875a3f73)

2023-05-10 04:58 UTC, richardolsson requested changes
We're getting closer but I still found one bug, and one code style issue that is related to my personal taste but I think is arguably better for readibility.

2023-05-10 04:58 UTC, richardolsson commented on src/features/events/components/ParticipantSummaryCard.tsx
> +          {new Date(eventData.start_time) > new Date() ? (
I find it very difficult to read these very large ternary expressions in the middle of JSX, and would appreciate if you can shorten it in one of several ways:

### 1. Separate components
Convert the contents to separate components (defined in the same module) and use as such:

```tsx
{new Date(eventData.start_time) > new Date() ? <ReminderInfo …/> : <AttendanceInfo …/>}
```

### 2. Functions
Move the contents to functions (defined inside of this component) and use as such:

```tsx
{new Date(eventData.start_time) > new Date() ? renderReminderInfo() : renderAttendanceInfo()}
```

2023-05-10 04:58 UTC, richardolsson commented on src/features/events/components/ParticipantSummaryCard.tsx
> +                  variant="h4"
This should only be visible when `noshowParticipants > 0`, as stated in the requirements in the issue.

2023-05-11 06:07 UTC, richardolsson commented on src/features/events/components/ParticipantSummaryCard.tsx
> +          {new Date(eventData.start_time) > new Date() ? (
I started working on this but decided to leave it as I think this component could do with a bigger refactor than what I have time to do right now.

2023-05-11 06:08 UTC, richardolsson approved these changes
Ready to merge! 🎉

2023-05-11 06:08 UTC, merged