Rename lists to views
zetkin/app.zetkin.org pull request #1554
Opened 2023-09-22 13:28 UTC by kaulfield23

## Description
This PR fixes a bug where it breaks localization in view

## Screenshots
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/331990a9-c220-496e-9d1b-fba5e232fda3)

## Changes

* Changes `lists` to `views`

## Notes to reviewer

## Related issues
Undocumented

2023-09-22 13:58 UTC, richardolsson requested changes
The changes to the `makeMessages()` prefix looks good to me, but I don't understand why we would need to change the test. They should be unrelated, and to me the test looked right before (using "list"). If that test failed, I believe that it's either flaky (retry it) or the code it's testing is wrong (fix it).

2023-09-22 14:01 UTC, kaulfield23 commented on integrationTesting/tests/organize/views/detail/create.spec.ts
> +    expect(viewPostLogs[0].data?.title).toEqual('New View');
The test failed there and result said it was expecing to have `New list` but the result was `New View` so I fixed it to `New View` @richardolsson

2023-09-22 14:03 UTC, kaulfield23 commented on integrationTesting/tests/organize/views/detail/create.spec.ts
> +    expect(viewPostLogs[0].data?.title).toEqual('New View');
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/1000083a-b597-4a6a-8b7d-aa4ce339559e)

2023-09-30 04:23 UTC, richardolsson approved these changes
I'm not sure why I didn't already review this, because it looks fine and simple!

2023-09-30 04:23 UTC, merged