WIP Experimentally implement hook to update org action needed status on a…
zetkin/app.zetkin.org pull request #1555
Opened 2023-09-25 08:09 UTC by ziggabyte

… call.

## Description
This PR…

## Screenshots
[Add screenshots here]

## Changes
[Add a list of features added/changed, bugs fixed etc]

* Adds…
* Changes…

## Notes to reviewer
[Add instructions for testing]

## Related issues
Resolves #[id]

2023-09-29 09:13 UTC, richardolsson commented
Here are my notes from our call the other day. Dumping them here so that I can get rid of them locally. 😊 

```
calendar        done
files           done
smartSearch     done
user            done

views           in progress (Haeju)
tasks           in review (Haeju) 
callAssignments in review (Ziggi)
tags            changes required (Haeju)
organizations   changes required (Rebeca)

events          in progress (Rebeca)
campaigns       not started (models, react-query)
journeys        not started (react-query)
profile         not started (react-query)
search          not started (react-query)
surveys         not started (models)
```

2023-09-30 18:35 UTC, rebecarubio commented on src/features/callAssignments/hooks/useCallAssignmentStats.ts
> +    error: getStats().error,
For me all this calls to `getStats()` look unnecessary. Is it possible to save the return of the function in a variable and work with that in the return? Like stats.data, stats.error or event just return the future object?

2023-09-30 18:36 UTC, rebecarubio commented on src/features/callAssignments/hooks/useCallers.ts
> +    isLoading: getFilteredCallers().isLoading,
Same here from my comment above

2023-09-30 18:41 UTC, rebecarubio requested changes
Good job refactoring this! My only concern as far as I can see it's the return of some functions, as I commented. I think that would fix some of the issues that @kaulfield23 has detected, like the disabled save in call instructions.

2023-09-30 18:51 UTC, kaulfield23 commented
Nice 👍 ! I've tested every hooks and its return values on web to see if everything works well. I have found a problem with call instructions that can't be updated. About codes, I also agree on Rebeca's comments! We assigned future values to a variable and returned that variable from hook. You can find those patterns in our codes!

2023-10-25 06:29 UTC, richardolsson commented
Once everything else has been merged into this, and before this is ready to merge with `main`, I think there are some additional cleaning tasks that could take place. I'm adding them here to remember, feel free to add to the list (or postpone them for later if you prefer):

- [ ] Get rid of `useModel()`, `ModelBase` and similar code
- [ ] Remove the `react-query` dependency
- [ ] Get rid of `ZUIQuery`

2023-10-26 08:53 UTC, richardolsson commented
Here's my analysis of the current situation.

Places that still rely on `react-query`:

- [ ] Breadcrumbs (I will fix)
- [ ] `ZUIPersonSelect` (I will fix)
- [ ] Search (I will fix)
- [ ] Profile page (I will fix)
- [ ] `EditCell` in `SurveySubmissionsList` (I will fix)
- [ ] `CampaignDetailsForm` (maybe you can investigate and fix, @ziggabyte?)
- [x] Journeys (being worked on by @ziggabyte)
- [x] Views (being worked on by @kaulfield23)
- [x] Smart Search (being worked on by @rebecarubio)


Places that still rely on models:
- [ ] `CallAssignmentStatusCard` (will you investigate, @ziggabyte?)
- [x] Views (being worked on by @kaulfield23)

2023-10-27 08:04 UTC, kaulfield23 commented
These things are need to be fixed
- A bug where a task can't be published when it has assigned targets by using smart search.
: line 96 to 101 in `src\pages\organize\[orgId]\projects\[campId]\calendar\tasks\[taskId]\assignees.tsx` needs to be fixed

- `UpdateColumnOrder` in `main` branch
: `UpdateColumnOrder` in `src\features\views\models\ViewDataModel.ts` and its relevant codes does not exist in this branch.

2023-10-31 15:15 UTC, richardolsson commented
Once #1603 is merged, I believe everything has been solved except this:

>  Address the situation in FetchAPIClient, line 94

This is not really a problem related to hooks/models/etc, it works ok without changes, and can be worked on at a later time. I can't really think of a great solution right now, so I'd like to postpone it and just leave the `TODO` comment that is already there.

2023-10-31 17:42 UTC, richardolsson commented
I've resolved all merge conflicts now. In the process I found a bug that I reported as #1604 and another that I fixed in d36b2ad.

2023-10-31 19:26 UTC, richardolsson approved these changes
I don't see how reviewing this huge PR is ever going to be feasible, so I'm just going to approve it based on the fact that all the individual sub-PRs that have lead up to it have been approved.

Let's merge!

2023-10-31 19:26 UTC, merged