Issue 1542/refactor tags hook
zetkin/app.zetkin.org pull request #1558
Opened 2023-09-26 12:05 UTC by kaulfield23

## Description
This PR refactors the `tagModel` into `useTag` hook.

## Screenshots

## Changes
[Add a list of features added/changed, bugs fixed etc]

* Create `useTag` and fix its relevant codes
* Delete `tagModel.ts`

## Notes to reviewer
Didn't delete `tagRepo` since `assignTagToPerson` is used in `ViewDataModel.ts`

## Related issues
part of issue-1542

2023-09-27 09:14 UTC, rebecarubio reviewed
Nice fix! This lgtm but I would like @richardolsson to double check, as we are getting familiar with this new pattern :)

2023-09-27 13:09 UTC, richardolsson requested changes
Nice work in general! There are some changes that I think would make the code cleaner though. I've commented below.

2023-09-27 13:09 UTC, richardolsson commented on src/features/tags/hooks/useTag.ts
> +  tagIsLoading: boolean;
The name of the hook already tells us that the hook will return a tag, so there is no need for these prefixes. I would call these properties:

```suggestion
  data: ZetkinTag | null;
  error: unknown | null;
  isLoading: boolean;
```

2023-09-27 13:09 UTC, richardolsson commented on src/features/tags/hooks/useTag.ts
> +  const getTag = () => {
This function is unnecessary. Inline it's contents inside the hook instead. You can just grab the return value from `loadItemIfNecessary` and use that further down the function where you are currently calling `getTag()`.

2023-09-27 13:09 UTC, richardolsson commented on src/features/tags/hooks/useTag.ts
> +  removeFromPerson: (personId: number) => Promise<void>;
I like how these mutation functions are returned.

2023-09-28 12:41 UTC, rebecarubio approved these changes
lgtm 🚀

2023-09-28 12:59 UTC, merged