Fix survey sorting
zetkin/app.zetkin.org pull request #1714
Opened 2023-12-16 10:56 UTC by alexandrakoch

## Description
This PR adds sorting for all survey fields using a `sortComparator` in the `makeSimpleColumn` function

## Changes
* Adds a `GridComparatorFn`, `alphabeticalComparator`, to `SurveySubmissionsList.tsx` to compare values alphabetically
* Adds a `sortComparator` (`alphabeticalComparator`) and `valueGetter` to the `makeSimpleColumn` function to enable alphabetical sorting for those columns

## Related issues
Resolves #1703

2023-12-21 15:53 UTC, kaulfield23 requested changes

2023-12-21 15:53 UTC, kaulfield23 commented on src/features/surveys/components/SurveySubmissionsList.tsx
> +  v1.localeCompare(v2);
Nice way that sorting with `sortComparator` that gets value from `valueGetter`! I just tested it, and got this error from `alphabeticalComparator` when there is no value in a cell.
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/38e5d46a-00fb-44f9-b210-759537c22ced)

2024-02-02 15:16 UTC, ziggabyte commented
@alexandrakoch do you wanna finish this, or should someone from the team take over? Either is fine :D

2024-02-15 10:31 UTC, ziggabyte approved these changes
I took over to finish the last bits of this! Great job getting it started! :D

2024-02-15 10:48 UTC, merged