Minor layout fixes for org-switcher side-bar
zetkin/app.zetkin.org pull request #1831
Opened 2024-03-16 11:32 UTC by ajoensson

## Description
This PR fixes an issue where the org-switcher chevron could disappear for long organization names, as well as the size of the filter in the org-switcher. The chevron is now always visible by truncating the organization name with an ellipsis if they are too long.

## Screenshots
Before the fix:
![Screenshot 2024-03-16 at 11 59 33](https://github.com/zetkin/app.zetkin.org/assets/5444360/6cbdf5aa-82ad-4c26-b455-c55b9ddc6369)

Fixed:
![Screenshot 2024-03-16 at 11 59 55](https://github.com/zetkin/app.zetkin.org/assets/5444360/98b35a75-95d9-44e3-97e6-62c66c85624e)

and it still works the same for short organization names
![Screenshot 2024-03-16 at 12 06 41](https://github.com/zetkin/app.zetkin.org/assets/5444360/e54f561d-97ef-4c0c-b416-526144d36bff)

The chevron now aligns whether expanded or not, since the filter input has the correct size:
![Screenshot 2024-03-16 at 12 23 57](https://github.com/zetkin/app.zetkin.org/assets/5444360/7e9d035a-0eb9-44d0-b9dd-421a5d95d710)

## Changes

* Update CSS in organization sidebar to add overflow behaviour for long organization names.
* Change size of organization switcher filter to match with unexpanded switcher.

## Notes to reviewer
In order to test the longer org name, you can do as follows (quoted from #1797):
> Change the name of the organization using a `PATCH /api/orgs/1` with `{ "title": "Organization With A Long Name" }` 

## Related issues
Resolves #1797, #1799

2024-03-16 16:45 UTC, richardolsson requested changes
Nice work! I'm seeing a small problem with this when the org name is long. When the title element grows, the margins around the avatar shrink. I see it very clearly in Chrome on the preview build (see screenshot below) but also in your screenshots, albeit less extreme.

![image](https://github.com/zetkin/app.zetkin.org/assets/550212/f6539bf5-09d8-4b5a-a49f-8dda4fed8ba1)

Would you mind looking into this? Let me know if you want me to show and/or explain more thoroughly.

2024-03-16 16:45 UTC, richardolsson commented on src/zui/ZUIOrganizeSidebar/index.tsx
> +                            size="small"
Great! This will please designer Josef. ✨

2024-03-17 08:43 UTC, ajoensson commented
It should be fixed now! PTAL!

2024-03-17 09:07 UTC, richardolsson approved these changes
Great! Lets get this merged!

2024-03-17 09:07 UTC, richardolsson commented on src/zui/ZUIOrganizeSidebar/index.tsx
> +                                flexShrink: 0,
Simple fix! ❤️

2024-03-17 09:08 UTC, richardolsson commented
Playwright is acting up this weekend. I have looked at the failing tests and they are notoriously flaky and unrelated to this fix, so I'm going to merge with 4/5 checks passing.

2024-03-17 09:08 UTC, merged