Issue 1722/sub org survey read only
zetkin/app.zetkin.org pull request #1941
Opened 2024-05-06 08:10 UTC by kaulfield23

## Description
This PR…

## Screenshots
[Add screenshots here]

## Changes
[Add a list of features added/changed, bugs fixed etc]

* Adds…
* Changes…

## Notes to reviewer
[Add instructions for testing]

## Related issues
Resolves #[id]

2024-05-10 08:54 UTC, richardolsson reviewed
Nice work! I began reviewing this but didn't finish so I didn't publish my comment. I'm publishing them now and will continue to review the rest of the PR as soon as I can, but most likely not until next week.

2024-05-13 08:32 UTC, kaulfield23 commented on src/pages/organize/[orgId]/projects/index.tsx
> +      !dayjs(survey.expires).isBefore(dayjs(), 'day')
In Figma there is a note about shared project that says 'Visible only when shared activities are available'. I interpreted this to mean that the 'Share with us' will only be visible when there are ongoing activities. I'm going to check with Josef!

2024-05-15 08:22 UTC, kaulfield23 commented
Come to think of it, I think <SharedCard/> should not be in survey dir. I will fix it today!

2024-05-24 15:34 UTC, richardolsson requested changes
Awesome work on this! I think it's really nice. I've looked at the code and played around with the preview build. There were some texts that I feel could be improved when I saw them in place, but then I think it's ready to merge!

2024-05-24 15:34 UTC, richardolsson commented on src/features/surveys/l10n/messageIds.ts
> +      'This survey is owned by {orgTitle} and it is not editable.'
Maybe a more direct text would be:

```suggestion
      'This survey is owned by {orgTitle} and you can not edit it.'
```

2024-05-24 15:34 UTC, richardolsson commented on src/features/surveys/l10n/messageIds.ts
> +      'This survey is owned by {orgTitle} and is editable only from its original location.'
```suggestion
      'This survey is owned by {orgTitle} and you can only edit it from its original location.'
```

2024-05-24 15:34 UTC, richardolsson commented on src/features/campaigns/components/SharedCard.tsx
> +            />
Nice solution!

2024-05-24 15:34 UTC, richardolsson commented on src/features/campaigns/l10n/messageIds.ts
> +      'This project contains only activities shared from other organizations and it is viewable only.'
```suggestion
      'This project contains only activities shared from other organizations and you can view it but not change it.'
```

2024-05-27 13:02 UTC, richardolsson submitted a review, later dismissed
With those minor changes to the messages I think this is ready to merge now. Nice work! 🎉

2024-05-27 13:36 UTC, kaulfield23 commented
Just fixed a merge conflict!

2024-05-27 13:37 UTC, richardolsson approved these changes
Full speed ahead! 🚀

2024-05-27 13:38 UTC, merged