Isssue 79/disable api coverage in prod
zetkin/app.zetkin.org pull request #199
Opened 2021-06-12 10:36 UTC by kjersti

If I understood the issue correctly, this should close #79

2021-06-12 11:35 UTC, olleolleolle approved these changes
👍 I am guessing that NODE_ENV production (aka "deployed somewhere") is the right thing here, since code coverage is only interesting in dev/testing environments.

Kudos!

2021-06-13 07:21 UTC, richardolsson requested changes
Great work! 💎 

I'm really impressed with how quickly you familiarized yourself with the environment and was able to sort this out.

I have a few comments below, and hope you can take a look at them before we merge?

2021-06-13 07:21 UTC, richardolsson commented on .env.test
> +NEXT_PUBLIC_CYPRESS=true
I would rename this to `CYPRESS` and set it's value to `1` for consistency (compare with `NEXT_PUBLIC_APP_USE_TLS`.

The `NEXT_PUBLIC_` prefix means that the variable will be compiled into the front-end bundle, i.e. be exposed to the browser. Although there is no security issue in exposing this particular variable to the browser, I think it only needs to be available to server-side code and we should avoid creating a pattern of exposing more than necessary.

2021-06-13 07:21 UTC, richardolsson commented on src/pages/api/coverage.ts
> +};
It looks like your editor has added a trailing newline in the file. This is not a big problem in itself, but it tells me that maybe your editor has not picked up the settings from the `.editorconfig` file. See the README for instructions/links on how to set that up. 😊

2021-07-16 06:53 UTC, kjersti commented
Let me know if there are any other issues! :)

2021-07-16 07:55 UTC, richardolsson requested changes
Thanks for changing this @kjersti! The environment variable is still referenced by it's old name in the source code so it needs to be changed there as well. See comment below. 👇

2021-07-16 07:55 UTC, richardolsson commented on src/pages/api/coverage.ts
> +    if (process.env.NODE_ENV === 'production' && !process.env.NEXT_PUBLIC_CYPRESS) {
The name of the variable needs to be changed here as well as a consequence of the change in 7fba7130dc4a80533dc38959d7960f6bd9d8bba3.

2021-07-16 07:57 UTC, richardolsson commented
Oh it looks like we found the same flaw. 😉 

I'm rerunning the CI tests and if all is well, will merge! Thank you @kjersti

2021-07-17 16:27 UTC, richardolsson approved these changes
Everything is looking great now! 💎 

Congratulations (and thank you) on your first merged pull request, @kjersti. 🙌

2021-07-17 16:28 UTC, merged