Issue 1992/emails in upcoming activities
zetkin/app.zetkin.org pull request #2007
Opened 2024-06-03 07:24 UTC by Jrende

## Description
This PR adds email activities to upcoming activities in the overview

## Screenshots
![upcomingemails](https://github.com/zetkin/app.zetkin.org/assets/1464855/a8557e1d-10fc-45da-9bda-d959567a7a36)

## Changes
* Adds emailActivities to the useActivityOverview hook

## Notes to reviewer
Also fixed a typo

## Related issues
Resolves #1992

2024-06-04 11:54 UTC, ziggabyte requested changes
Great work!! 

Even though the hope is that this would be as easy as a fix on two little lines, when I play with it today I'm seeing something that makes me think there is some work to be done in this area. 

My guess is that some logic regarding the send-time of the email is being miscalculated, making an email that was sent three hours today ago appear in both the column for today and the column for tomorrow: 
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/e7b98c68-a7da-4e20-a5dd-ff4a32bff3cd)

I also think that the sentence at the bottom of the cards, that reads "Starts today" and "Ends in 21 hours" in this screenshot, is not optimal sentences for the emails. I think it should say "Will be sent tomorrow", "To be sent today" or "Was sent today" depending on the time of day. 

Would you like to investigate both the logic that makes the email appear in two columns at once, and the possibilities to customise the message at the bottom?

2024-06-04 13:39 UTC, Jrende commented
> Great work!!
> 
> Even though the hope is that this would be as easy as a fix on two little lines, when I play with it today I'm seeing something that makes me think there is some work to be done...
> 
> My guess is that some logic regarding the use of the send-time of the email in the "tomorrow" column is wrong, making an email that was sent three hours ago today appear in both the column for today and the column for tomorrow: ![bild](https://private-user-images.githubusercontent.com/58265097/336436283-e7b98c68-a7da-4e20-a5dd-ff4a32bff3cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDg1ODUsIm5iZiI6MTcxNzUwODI4NSwicGF0aCI6Ii81ODI2NTA5Ny8zMzY0MzYyODMtZTdiOThjNjgtYTdkYS00ZTIwLWE1ZGQtZmY0YTMyYmZmM2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDEzMzgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Nzk5OTlkNWY0YzAwZTI4M2M4NzE5MjRjY2QxYjgyODA2OGNiYTgyNWU4OTM5MzI4OTc4YjQxNjc3ODY2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hte5mtgpFF1BOTxdvfbp2i6ZkKp0-sqa7CQy2savjvM)
> 
> I also think that the sentence at the bottom of the cards, that reads "Starts today" and "Ends in 21 hours" in this screenshot, is not optimal sentences for the emails. I think it should say "Will be sent tomorrow", "To be sent today" (or maybe "To be sent in xx hours"?) or "Was sent today" (or "Was sent xx hours ago"?) depending on the time of day.
> 
> Would you like to investigate both the logic that makes the email appear in two columns at once, and the possibilities to customise the message at the bottom?

So it was actually a medium-length task ;)
I can keep working on it to fix those issues.

2024-06-08 09:23 UTC, Jrende commented
![Screenshot_2024-06-08_11-13-51](https://github.com/zetkin/app.zetkin.org/assets/1464855/8122b878-8985-4f7d-92f9-905935f638cf)
I've customized the message for email activities and made sure that they are only visible for one day

2024-06-08 09:28 UTC, Jrende commented on src/utils/dateUtils.ts
> +  return dayjs(first).isSame(dayjs(second), 'day')
This change might look dangerous. The reason I did it was that doing 
`(new Date("2024-06-08T00:00:00").toISOString().slice(0, 10))` returns "2024-06-07" due to it taking time zones into account. Using `isSame` with 'day' as parameter fixed that, and to me it feels more safe to handle comparisons using a date library.

2024-06-10 10:22 UTC, ziggabyte requested changes
Nice with the messages and the work on the dates! Almost there!

I noticed another small thing when playing with it - the little colour dot should be blue as long as the email is scheduled (not sent) and green only after it has been sent. Now it is green on the day it is going to be sent, even if it is not sent already. 

![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/6147811d-3489-467c-b546-bbcde24c0091)

would you like to investigate this and see how this could be changed so we get the right colour for before and after being sent?

2024-06-10 10:22 UTC, ziggabyte commented on src/utils/dateUtils.ts
> +  return dayjs(first).isSame(dayjs(second), 'day');
I think it makes a lot of sense like you say to let a library handle the comparisons of dates! I did not know of the `endOf` and `startOf` functions in dayjs that you used in the other place, very convenient!

2024-06-17 16:10 UTC, ziggabyte approved these changes
Great job with this! Just to make sure it would make it into the next release I took on the task of fixing the colors of the status dots (which is a deeper issue that needs more harmonizing in the project in general - but, that's for another day). 

So nice to have you contributing on the project when the time and energy allows :D

2024-06-17 16:14 UTC, merged

2024-06-28 06:54 UTC, Jrende commented
I realized that I forgot about this ticket, thank you for doing the final step!