Implementing the new design system
zetkin/app.zetkin.org pull request #2111
Opened 2024-08-26 07:39 UTC by ziggabyte

## Description
This PR is the WIP of the implementation of the new Zetkin design system, designed by @theo-organism . 

This is the main to-do list of the work being done

- [ ] New header
    - [ ] ZUIMenu
    - [ ] ZUIButton
    - [ ] ZUIButtonGroup
    - [ ] ZUIBreadcrumbs
    - [ ] ZUIStatusChip
- [ ] New font 
    - [ ] ZUIText
    - [ ] Styles for text in ZUI 
- [ ] New colors
- [ ] ... and more

## Screenshots
Will be added 

## Changes
* LOADS of things

## Notes to reviewer
[Add instructions for testing]

## Related issues
Resolves #[id]

2024-09-29 04:35 UTC, richardolsson commented
Here's how you can solve the problem with Vercel not wanting to deploy storybook on this branch (and it's derivative branches):

```patch
diff --git a/.storybook/main.js b/.storybook/main.js
index 3be891c07..bc6155896 100644
--- a/.storybook/main.js
+++ b/.storybook/main.js
@@ -4,7 +4,8 @@ module.exports = {
   staticDirs: ['../src'],
   stories: [
     '../src/**/*.mdx',
-    '../src/zui/!(ZUITimeline|ZUITextEditor|ZUIRelativeTime|ZUIReorderable|ZUISection|ZUIUserAvatar|ZUIDialog|ZUIEllipsisMenu|ZUIFileChip|ZUIJourneyInstanceItem|ZUIList|ZUILogo|ZUIPerson|ZUIPersonAvatar|ZUIPersonLink|ZUIPreviewableInput|ZUIAccessList|ZUIEmptyState|ZUIStackedStatusBar|ZUISuffixedNumber|ZUITimeSpan|ZUIAccessList|ZUIJourneyInstanceCard|ZUIAnimatedNumber|ZUIConfirmDialog|ZUIAutoTextArea|ZUICollapse|ZUIDate)/**/*.stories.@(js|jsx|ts|tsx)',
+    '../src/zui/!(ZUIAccessList|ZUIJourneyInstanceCard|ZUIAnimatedNumber|ZUIConfirmDialog|ZUIAutoTextArea|ZUICollapse|ZUIDate)/**/*.stories.@(js|jsx|ts|tsx)',
+    '../src/zui/!(ZUITimeline|ZUITextEditor|ZUIRelativeTime|ZUIReorderable|ZUISection|ZUIUserAvatar|ZUIDialog|ZUIEllipsisMenu|ZUIFileChip|ZUIJourneyInstanceItem|ZUIList|ZUILogo|ZUIPerson|ZUIPersonAvatar|ZUIPersonLink|ZUIPreviewableInput)/**/*.stories.@(js|jsx|ts|tsx)',
   ],
   addons: [
     '@storybook/addon-links',

```

2024-10-12 05:37 UTC, richardolsson commented
Note to @ziggabyte the ZUI Zsar:

I had to delete `ZUIToggleButton/index.stories.tsx` file because it was empty and prevented the build to work. This also lead me to believe that maybe you have forgotten to refactor `ZUIToggleButton` after merging #2212?

I will uncheck the checkbox from the todo list so we don't forget it.

2024-10-13 10:14 UTC, ziggabyte commented
> Note to @ziggabyte the ZUI Zsar:
> 
> I had to delete `ZUIToggleButton/index.stories.tsx` file because it was empty and prevented the build to work. This also lead me to believe that maybe you have forgotten to refactor `ZUIToggleButton` after merging #2212?
> 
> I will uncheck the checkbox from the todo list so we don't forget it.

I just saw this now! This is the thing I said on wednesday that i was almost almost finished with but needed to fix some css that i ragequitted 😂 I figured out how to make it work now and made a PR with the changes!

2024-11-13 12:12 UTC, ziggabyte commented
> # ZUIDivider
> 
>     * The `middle` variant should look like what the current `fullWidth` looks like.
> 
>     * The `fullWidth` should extend to the very edge of the card.
> 

This has to do with padding of the box that Storybook stories are rendered in. The `fullWidth` version of the `ZUIDivider` does go to the edge of the div that it is in, it's just that that div is inside of another div (by Storbook) that has some padding, which means it does not look like it goes "all the way". I can update the example to add a border around the div where the text and dividers are rendered, to make it more clear that they do go all the way to its closest parent.

2024-11-13 15:16 UTC, thepeno commented
# ZUIIcon

## Wanted
- [ ] Medium icon should be 24px width and height.
- [ ] Large icon should be 35px width and height.

(These are default sizes from MUI)

2024-12-28 16:42 UTC, richardolsson commented
I just merged #2450 into `main`, which means that Storybook is now included in the automatic app dev/preview builds (e.g. https://app.dev.zetkin.org/storybook). This means that we can (soon) disable the separate storybook build.

This PR is so dependent on storybook builds, so I won't disable the separate builds until this PR has merged in `main` the next time. But after that, we can disable the storybook builds and just always use the /storybook link to access storybook.

2025-02-10 14:36 UTC, richardolsson commented
Storybook is available at `/storybook` on the app-zetkin-org builds from now on. For example, storybook on the most recent preview build:
https://app-zetkin-n9gje4q8t-zetkin.vercel.app/storybook

2025-03-29 14:31 UTC, richardolsson commented
Is it a mistake that "Sections" is listed both as priority 1 and 2, or is it there to remind us of something? 😊

2025-03-30 06:20 UTC, ziggabyte commented
> Is it a mistake that "Sections" is listed both as priority 1 and 2, or is it there to remind us of something? 😊

Schrödinger's Sections :)

2025-04-11 15:27 UTC, richardolsson requested changes
I thought we were ready, but we're not. 😞

2025-04-11 15:27 UTC, richardolsson commented on tsconfig.json
> +    "src/zui/theme",
This needs to be reverted before we can merge, otherwise we disable typescript in all of the program code. I tried reverting it locally and got 596 errors in 256 files. 😭

2025-04-12 05:28 UTC, richardolsson approved these changes
The time has come! Lets merge this main and get everyone testing that things still work. Next step after that: Implement ZUI in activist portal pages! 💯

2025-04-12 05:29 UTC, merged