allow import files to have both Zetkin ID and external ID
zetkin/app.zetkin.org pull request #2201
Opened 2024-09-28 15:32 UTC by remipou

## Description
This PR allows to select both zetkinID and externalId when importing files

## Screenshots

## Changes
- allow selecting both IDs
- add "member_id" to the person fields (as "ext_id" was previously called "member_id")
- fix a typo

## Notes to reviewer

## Related issues
Resolves #1935 (https://github.com/zetkin/app.zetkin.org/issues/1935)

2024-09-28 16:08 UTC, remipou commented
I added "member_id" into some types, it should be removed when the backend replies with "ext_id" instead of "member_id" like it should? @richardolsson

2024-09-29 09:01 UTC, richardolsson requested changes
Great work on this! You've managed to solve some things, but I realized as I was playing around with it that it also causes some other problems. I've left some comments below. Do you think you could take a look at them? Please feel free to come talk to me if you have any questions!

2024-09-29 09:01 UTC, richardolsson commented on src/features/import/hooks/useColumn.ts
> -
At first I thought, what a beautifully simple solution. But then I realized, wait, doesn't this mean you can pick multiple "External IDs", and yes you can. It should be possible to pick one Zetkin ID and one External ID, but no more than that. But right now you can:

![image](https://github.com/user-attachments/assets/f94803a9-1022-4051-88cb-4471aac67906)

(ignore the fact that I've used completely nonsensical data in my screenshot above)

I don't know how best to solve this. I guess we could merge without making any changes to this, but I would ideally like to at least prevent the user from clicking the "VALIDATE" button if there are more than one Zetkin ID and/or more than one External ID.

Would you mind trying to add logic for that? And then maybe create a separate issue for coming up with an even better solution at some later point in time?

2024-09-29 10:08 UTC, remipou commented on src/utils/types/zetkin.ts
> +  member_id?: string | null;
this should solve it? https://github.com/zetkin/app.zetkin.org/pull/2201/commits/272f9c0f00a194ce4fe1a5fefa189de43177e03d

2024-09-29 11:19 UTC, remipou commented
ready for review @richardolsson

2024-12-03 04:33 UTC, richardolsson commented
Superseded by #2391, where @ziggabyte started from this great work, fixed a merge conflict and made some minor changes to the UX.

2024-12-03 04:33 UTC, closed without merging