Add event title to event page header
zetkin/app.zetkin.org pull request #2261
Opened 2024-10-13 11:24 UTC by dev-di

## Description
Adding the event title to the page title

## Screenshots
<img width="959" alt="image" src="https://github.com/user-attachments/assets/15adfdb1-ca13-41ed-b981-95e301d58052">

## Changes
Title added to event header

## Notes to reviewer
Verify that the event page is showing the event page title (instead of the address)

## Related issues
Resolves #2258

2024-10-13 13:34 UTC, niklasva82 requested changes

2024-10-13 13:34 UTC, niklasva82 commented on src/features/events/layout/EventLayout.tsx
> +        <title> {eventFuture.data?.title} </title>
Ah I believe I forgot to tell you. If there is no title, the title should use the activity title, and if that's not available, it should use the noTitle message.

Here is an example of how this is implemented:
https://github.com/zetkin/app.zetkin.org/blob/c279be9988118c47fe8d1db5e6339914aefb16d2/src/features/events/components/EventPopper/SingleEvent.tsx#L132

2024-10-14 17:14 UTC, richardolsson requested changes
The solution looks good! But the CI isn't passing because the code formatting does not follow the "Prettier" code style. Please try running `yarn prettier --write src` and then commit the changes.

2024-10-15 08:27 UTC, richardolsson approved these changes
Nice work!

I have tried the preview build, and also reviewed the code (thank you GitHub for the beautiful "Hide whitespace" feature) and it all looks good.

Lets get this merged! 💯 

Congratulations on your first(?) code contribution to Zetkin! 🎉

2024-10-15 08:28 UTC, merged