Issue 425/form error handling
zetkin/app.zetkin.org pull request #437
Opened 2021-09-24 10:35 UTC by djbusstop

Changes:
- Move all forms in to `components/forms` (not sure if best idea, just flattens out the component folder heirarchy.)
  -  In process, renames forms to use `<Model><Action>Form` format
- `TaskDetailsForm`
  - [x] Tests successfully posting Offline Task
  - [ ] Tests that error alert shows when posting task returns error from server
  - [ ] Tests that submit button only enabled when there are no validation errors

Todo:
- [ ] All forms submit button should only be enabled if no errors
- [ ] Submit and Cancel button components

2021-09-28 11:36 UTC, djbusstop commented
Forms to change:

- Create Campaign
- Edit Campagaign
- Delete Campaign

- Create Task
- Edit Task
- Delete Task
- Publish Task

2021-10-05 07:06 UTC, richardolsson requested changes
Awesome work on this! I found some minor mistakes (I think?) and had one idea on how to improve the tests that submit forms, but other than that this is spotless.

2021-10-05 07:06 UTC, richardolsson commented on src/components/organize/campaigns/CampaignActionButtons.tsx
> +import { FormattedMessage, FormattedMessage as Msg, useIntl } from 'react-intl';
This is importing `FormattedMessage` twice.

2021-10-05 07:06 UTC, richardolsson commented on src/components/organize/tasks/TaskActionButtons/index.tsx
> +import { FormattedMessage, FormattedMessage as Msg, useIntl } from 'react-intl';
`FormattedMessage` is being imported twice.

2021-10-05 08:03 UTC, djbusstop commented on playwright/tests/organize/campaign-detail/action-buttons.spec.ts
> +test.describe.only('Campaign action buttons', async () => {
nope!

2021-10-05 13:03 UTC, richardolsson approved these changes
LGTM! Ready to merge!

2021-10-05 13:03 UTC, merged