Sort and filter querystring
zetkin/app.zetkin.org pull request #763
Opened 2022-06-19 14:55 UTC by richardolsson

## Description
This PR adds logic to reflect the sort and filter state of a `UserConfigurableDataGrid` in the querystring of the page.

## Screenshots
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/550212/174486995-c2ec9279-b6b4-4268-9548-03f037e8fd12.png">

## Changes
* Adds a new `useModelFromQueryString()` hook
  * Serializes any changes to `sortModel` and `filterModel` and updates the query string
  * Parses the deserialized `router.query` when it changes, and updates the state of the `sortModel` and `filterModel`
* Uses the new hook in `UserConfigurableDataGrid`
* Fixes some issues with using querystrings in our URLs:
  * Fixes an issue in `TabbedLayout` which was not considering the querystring when comparing the current path and `basePath` to figure out whether the current tab was the "home" tab
  * Disables the `NProgress` progress bar when the router is navigated using `shallow: true`, i.e. when there is no loading happening before navigation
  * Changes how breadcrumbs are cached, so that only the query parameters that come from the path (not the query string) are used

## Notes to reviewer
This should work both for Views and Journey instances.

## Related issues
Resolves #736

2022-06-20 04:56 UTC, richardolsson commented
What kind of tests do you reckon we need for this, @djbusstop?

How about a single playwright test which sorts and filters journey instances, then refreshes and verifies that the sort and filter state is still there, and/or goes back to verify that the state changes back. That way, we're not testing implementation at all, just the user experience?

2022-06-20 08:32 UTC, djbusstop commented
> How about a single playwright test which sorts and filters journey instances,

I think this is a great idea! Simple. Also, amazing work on this. Super clean, I don't have any comments on the code.

2022-06-20 09:05 UTC, lowlandjuju requested changes
Nice query string interface - readable for power users and not too verbose either 👍 

The bug highlights maybe that the query string hook itself could use some testing to cope with as many possible combinations of filters and sorting as you can think of? It feels like the place to test, but I didn't establish where the bug originates, so it might be somewhere else...

x

2022-06-20 12:59 UTC, richardolsson commented on src/components/UserConfigurableDataGrid/useModelsFromQueryString.ts
> +export function useModelsFromQueryString(): UseModelsFromQueryString {
Well spotted! Probably related to filtering twice on the same column. Will investigate and I have a good hunch of what is causing this.

2022-06-20 13:36 UTC, richardolsson commented
I have added a playwright test to make sure the state is persisted, fixed the bug found by @lowlandjuju, and added tests to verify it's fixed.

2022-06-22 08:03 UTC, lowlandjuju approved these changes
Looks ready for merging 👍 😁

2022-06-22 10:26 UTC, merged