Issue 548/distinguish zetkinuser and zetkinperson in mocks
zetkin/app.zetkin.org pull request #791
Opened 2022-08-18 16:17 UTC by ziggabyte

## Description
This PR does a bit of house cleaning in the mocks department, especially in regards to making it more obvious if you're referencing a ZetkinPerson or ZetkinUser.

## Changes
* Creates a RosaLuxemburgUser-mock to be used in the few places where a ZetkinUser is needed. 
* Removes a file of unused mocks. 
* Updates mocks to be more streamlined, replacing strings and hardcoded objects with other mocks. 

## Related issues
Resolves #548

2022-08-26 07:29 UTC, richardolsson requested changes
I think this looks mostly good. We do have a problem with mock data containing more fields than actual API data, meaning that in theory tests could be falsely positive.

But the types are correct so I don't think it's a huge problem because typescript would catch any misuse of data before the tests even run.

2022-08-26 07:29 UTC, richardolsson commented on playwright/tests/organize/memberships.spec.ts
> +    login(RosaLuxemburgUser, memberships);
This is correct!

2022-08-26 07:29 UTC, richardolsson commented on playwright/tests/organize/memberships.spec.ts
> +            RosaLuxemburgUser.first_name + ' ' + RosaLuxemburgUser.last_name,
Same issue as above.

2022-08-26 10:48 UTC, ziggabyte commented on playwright/tests/organize/memberships.spec.ts
> +            RosaLuxemburgUser.first_name + ' ' + RosaLuxemburgUser.last_name,
Aha! You caught one i did not see when going throught this! Thank you!

2022-08-31 08:27 UTC, richardolsson approved these changes
Great! 💯

2022-08-31 08:27 UTC, merged