Issue 795/collapse expand summary
zetkin/app.zetkin.org pull request #800
Opened 2022-08-30 15:51 UTC by ziggabyte

## Description
This PR adds a ZetkinCollapse component, that conditionally renders its children with a "show more/show less"-button, if the content of the children is higher than the height sent in to the component.

## Screenshots
![bild](https://user-images.githubusercontent.com/58265097/187471396-2a7f6974-f29d-476a-9e55-dec12fb192d2.png)
![bild](https://user-images.githubusercontent.com/58265097/187471466-e20bc137-e688-4d6c-97fa-c0b18ecde6ae.png)

## Changes
* Adds a ZetkinCollapse component
* Adds a storybook story for this component
* Changes JourneyInstanceSummary and PrettyEmail components to use ZetkinCollapse
* Adjusts font size in the summary

## Related issues
Resolves #795

2022-08-30 15:54 UTC, ziggabyte commented
Question i have: should this be applied to TimelineJourneyInstance component? From reading it it seems to do similar things with a "read more" button, but it looks like it has some auto-closing logic in there. Streamline to use ZetkinCollapse, or leave as is?

2022-08-31 08:26 UTC, richardolsson requested changes
This looks great! There's just a super tiny code hygiene thing concerning the name of the props interface in the new component. Then I'm ready to merge!

2022-08-31 08:26 UTC, richardolsson commented on src/components/Timeline/updates/elements/PrettyEmail.tsx
> +        </ZetkinCollapse>
Love it!

2022-08-31 08:48 UTC, ziggabyte commented on src/components/ZetkinCollapse.tsx
> +interface ZetkinCollapse {
Ofcourse! Must have slipped me when I changed the name of the component :)

2022-08-31 09:44 UTC, richardolsson approved these changes
Ready to merge IMO! 🎉

2022-08-31 09:47 UTC, merged