Issue 824/targeting targets section
zetkin/app.zetkin.org pull request #848
Opened 2022-11-28 15:31 UTC by ziggabyte

## Description
This PR adds a targets section to the call assignments targeting screen.

## Screenshots
![bild](https://user-images.githubusercontent.com/58265097/204316552-bbbb8a2b-90f8-41c5-ab6f-d579e06318d8.png)

## Changes
* Adds CallAssignmentTargets component, that lets users open a smart search dialog to create or edit their targeting query.
* Adds a setTargets method on the Call assignment model
* Adds a few colors from the designs to the Theme

## Notes to reviewer
This MVP version does not include the pictogram, that will later be in this section.

## Related issues
Resolves #824

2022-11-28 16:13 UTC, richardolsson requested changes
All in all this is great, but I did find a color reference that I found odd, and the invalidation doesn't quite work the first time a target is defined. 

Steps to reproduce:

1. Navigate to a call assignment
2. Edit targeting to only include "Start with an empty list"
3. Save targeting, verify that target box renders in the "define" state
4. Refresh page (important) to clear redux cache
5. Edit targeting to include people, e.g. change to "everyone in the organization"
6. Save targeting

Expected results: Stats should update
Actual results: Stats remain static

See comment below on where I think the problem is.

2022-11-29 09:02 UTC, ziggabyte commented on src/features/callAssignments/components/CallAssignmentTargets.tsx
> +    color: 'secondary',
ah, will remove

2022-11-29 09:02 UTC, ziggabyte commented on src/features/callAssignments/components/CallAssignmentTargets.tsx
> +            <Box bgcolor="background.secondary" p={2}>
i just tried to copy the figma design, where the inactive version had this color in the background.

2022-11-29 09:05 UTC, ziggabyte commented on src/theme.ts
> +    secondary: 'rgba(0,0,0,0.04)',
just made it to copy the figma design, can remove without nostalgia :D

2022-11-29 09:06 UTC, ziggabyte commented on src/features/callAssignments/store.ts
> +      ) {
thank you for catching this!

2022-11-29 12:46 UTC, richardolsson commented on src/features/callAssignments/components/CallAssignmentTargets.tsx
> +            <Box bgcolor="background.secondary" p={2}>
Actually, ignore this!

2022-11-29 12:46 UTC, richardolsson commented on src/theme.ts
> +    secondary: 'rgba(0,0,0,0.04)',
You're right! Leave it. 😊

2022-11-29 14:59 UTC, richardolsson approved these changes
Awesome! 💯

2022-11-29 14:59 UTC, richardolsson commented on src/pages/api/callAssignments/targets.ts
> +    doneButBlocked;
Nice!

2022-11-29 15:01 UTC, merged