View cell for Survey optionS #907
zetkin/app.zetkin.org pull request #971
Opened 2023-02-07 14:29 UTC by rebecarubio

## Description
This PR implements `survey_options` view cells. It means that it renders all options that a person selected for that question in the view and a counter with the total number of the selected options. Special thanks to @Bagera for make the styles of the chips (they break when they don´t fit in the cell and there´s also a ellipsis when can´t be displayed more options, see screenshots)

## Screenshots
![b-1](https://user-images.githubusercontent.com/36491300/217271263-a968c4f3-2304-4ef6-82e8-d895341554aa.PNG)
![b-with ellipsis](https://user-images.githubusercontent.com/36491300/217271306-69e574bf-489a-4107-92e0-eff26bedd164.PNG)
![b-popover](https://user-images.githubusercontent.com/36491300/217271345-6862c6cc-c4ed-4b81-a1fb-5e2163ea51da.PNG)

## Changes
* Adds `survey_options` type cell for `survey_options` column and styles for the cell
* Fixes bug in `surveyResponseColumnType` to filter empty cells

## Related issues
Resolves #907

2023-02-07 17:28 UTC, richardolsson requested changes
I think this looks super good except for a little bit of missing margins between the chips in the preview. Is that something that could be amended?

2023-02-07 17:28 UTC, richardolsson commented on src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx
> +                  <Chip key={s.id} label={s.text} variant="outlined" />
I think these chips need a little margins between them. 
![image](https://user-images.githubusercontent.com/550212/217319399-e58ed687-ab2d-485f-a51e-a7b55942f86d.png)

2023-02-08 07:31 UTC, rebecarubio commented on src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx
> +                  <Chip key={s.id} label={s.text} variant="outlined" />
sure! good idea!

2023-02-08 07:40 UTC, rebecarubio commented on src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx
> +                  <Chip key={s.id} label={s.text} variant="outlined" />
![margins](https://user-images.githubusercontent.com/36491300/217464416-ddd9c7c9-afa4-498c-9127-2e31042f35dd.PNG)

2023-02-08 07:49 UTC, richardolsson commented on src/features/views/components/ViewDataTable/columnTypes/SurveyOptionsColumnType.tsx
> +                  <Chip key={s.id} label={s.text} variant="outlined" />
Nice! 💯

2023-02-08 08:47 UTC, richardolsson approved these changes
It's looking good and I like it! 💯

2023-02-08 08:52 UTC, merged