Categorize column choices
zetkin/app.zetkin.org pull request #973
Opened 2023-02-07 17:21 UTC by richardolsson

## Description
This PR implements categorization of column choices, adds some new choices and improves some text.

## Screenshots
![image](https://user-images.githubusercontent.com/550212/217316533-b3880755-5160-4960-aa04-37a18f7d2e84.png)

## Changes
* Refactors column choices code
  * Separates code into multiple files for easier browsing and reading
  * Switches to using an object map instead of an array for choices
* Separates choices into categories
* Adds some shortcut field choices for creating email and phone fields
* Adds some prefabricated smart search queries
* Fixes a bug causing columns to be created in the wrong order (mentioned in #965)

## Notes to reviewer
Please feedback on the texts!

I made some changes compared to what we agreed on the issue:

* Instead of having "first name" and "last name" alongside "full name", I made it so that the "full name" option will be enabled if either field is missing, and add the missing one(s)
* Instead of putting "email" and "phone" under "Outreach", I put the "Pick field" choice so that the user can pick any field with just a single choice

## Related issues
Resolves #958

2023-02-08 10:59 UTC, ziggabyte commented
Input from looking at and thinking about the names and feel of the dialog: 
Add a short description to email and phone number (just because it looks too empty otherwise)

Custom x-ref description: "See if each person appears in a Smart Search query."
Reached on phone description: "Have we ever reached them when phonebanking?"
Survey response + Survey Responses - rename to "One question" and "Many questions"

2023-02-08 11:23 UTC, ziggabyte requested changes
what a nice refactor of the choices and categories! I ask for a small refactor but that is actually my own fault, so apologies for that 😅

2023-02-08 11:23 UTC, ziggabyte commented on src/locale/misc/views/en.yml
>      surveyResponse:
I put my comments about texts in a separate comment above!

2023-02-08 11:23 UTC, ziggabyte commented on src/features/views/components/ViewColumnDialog/ColumnGallery/SearchResults.tsx
> +              color={alreadyInView ? 'gray' : searchResult.color}
This is my mistake, for not saying when asking you to do this: the "gray" should be replaced by "theme.palette.onSurface.disabled"

2023-02-08 14:13 UTC, rebecarubio commented
> ponses - should be different

Super good job categorizing all the choices, it looks brilliant and it´s more understandable✨ ! I agree with all that @ziggabyte had suggested, I could only add that we have talked to change color and icon for the `Survey Responses` choice, to be the same as `Delegate` 
![image](https://user-images.githubusercontent.com/36491300/217553757-a229df11-8fef-4eab-ae3e-5708b16f6418.png)

2023-02-09 10:03 UTC, ziggabyte requested changes
A few detail comments, open for discussion on all of them. 

This does highlight the faults in the logic we created for colors (blue - 1 column, purple - 2 columns, red - multi columns) since there are choices that add 1, 2 or more columns. I think it's fine that there are inconsistensies in this now, it needs more dedicated thought at a separate time.

2023-02-09 13:46 UTC, ziggabyte approved these changes
LET'S GOOOOOO!!!

2023-02-09 13:50 UTC, merged